In [1]:
import numpy as np

# Using nditer
arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr):
    print(element)

1
2
3
4


In [12]:
import numpy as np



arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='C'):
    print(element)

    arr = np.array([[1, 2], [3, 4]])
new_arr = arr.reshape(2, 2)
print (new_arr)

1
2
3
4
[[1 2]
 [3 4]]


In [17]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='F'):
    print(element)


print (arr)

1
3
2
4
[[1 2]
 [3 4]]


import numpy as np

arr = np.array([[1, 2], [3, 4]])
new_arr = arr.reshape(2, 2)
    
for element in np.nditer(arr, order='F'):
    print(element)


    

In [18]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

print("The original 2D array:")
print(arr)

fortran_elements = []
for element in np.nditer(arr, order='F'):
    fortran_elements.append(element)

fortran_ordered_2d = np.array(fortran_elements).reshape(arr.shape)

print("\nElements in Fortran order (reshaped to 2D):")
print(fortran_ordered_2d)

The original 2D array:
[[1 2]
 [3 4]]

Elements in Fortran order (reshaped to 2D):
[[1 3]
 [2 4]]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# Get elements in Fortran order and reshape them into a 2D array
fortran_ordered_2d = arr.flatten(order='F').reshape(arr.shape)

print("Elements in Fortran order (reshaped to 2D):")
print(fortran_ordered_2d)

In [20]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
for x in np.nditer(arr):
  print(x)

for idx, x in np.ndenumerate(arr):
  print(idx, x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
