In [ ]:
import numpy as np

student1 = np.array([50,60])

student2 = np.array([70,80])

arr = np.concatenate((student1, student2)) # Removed axis = 1
print(arr)
max_marks = np.max(student1)
max_marks1 = np.max(student2)

print(max_marks)
print(max_marks1)

[50 60 70 80]
60
80


In [ ]:
import numpy as np

# Marks of 2 students in 2 subjects
marks = np.array([[50, 60],
                  [70, 80]])

# Student-wise total (axis=1)
student_total = np.sum(marks, axis=1)
print("Student-wise total:", student_total)

# Subject-wise total (axis=0)
subject_total = np.sum(marks, axis=0)
print("Subject-wise total:", subject_total)

# Student-wise maximum marks
student_max = np.max(marks, axis=1)
print("Student-wise maximum:", student_max)

Student-wise total: [110 150]
Subject-wise total: [120 140]
Student-wise maximum: [60 80]


In [ ]:
import numpy as np

# Crop yields for 4 farms over 5 seasons (in tons)
crop_yields = np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],  # Farm 1 - North Region
    [10.3, 11.5, 10.8, 12.1, 11.9],  # Farm 2 - South Region
    [15.1, 14.8, 16.2, 15.5, 16.8],  # Farm 3 - East Region
    [11.2, 10.9, 12.3, 11.7, 12.8]   # Farm 4 - West Region
])

print('Crop Yields Array (tons):')
print(crop_yields)
print(f'\nShape: {crop_yields.shape}')
print(f'Data type: {crop_yields.dtype}')
print(f'Total elements: {crop_yields.size}')
print(f'Number of dimensions: {crop_yields.ndim}')

# Agricultural analysis operations
total_yield = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields, axis=1)
avg_yield_per_season = np.mean(crop_yields, axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(f'\nTotal production: {total_yield} tons')
print(f'Average per farm: {avg_yield_per_farm} tons')
print(f'Average per season: {avg_yield_per_season} tons')
print(f'Maximum yield: {max_yield} tons')
print(f'Minimum yield: {min_yield} tons')

# Find best performing farm
best_farm = np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm: Farm {best_farm + 1}')
print(f'Their average yield: {avg_yield_per_farm[best_farm]:.2f} tons')

Crop Yields Array (tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape: (4, 5)
Data type: float64
Total elements: 20
Number of dimensions: 2

Total production: 262.7 tons
Average per farm: [13.76 11.32 15.68 11.78] tons
Average per season: [12.275 12.6   13.35  13.275 14.175] tons
Maximum yield: 16.8 tons
Minimum yield: 10.3 tons

Best performing farm: Farm 3
Their average yield: 15.68 tons
