In [ ]:
import numpy as np


In [ ]:
# From Python list
arr = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros = np.zeros((3, 4))         # 3x4 array of zeros
ones = np.ones((2, 3))           # 2x3 array of ones
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
identity = np.eye(3)             # 3x3 identity matrix
random_arr = np.random.rand(3, 4)# Random values between 0 and 1

In [ ]:
display(arr)

array([1, 2, 3, 4, 5])

In [ ]:
display(arr_2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
display(zeros)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones=np.zeros

In [ ]:
# From Python list
arr = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros = np.zeros((3, 4))         # 3x4 array of zeros
ones = np.ones((2, 3))           # 2x3 array of ones
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
identity = np.eye(3)             # 3x3 identity matrix
random_arr = np.random.rand(3, 4)# Random values between 0 and 1

In [ ]:
zeros=np.zeros((0,0))

In [ ]:
display(zeros)

array([], shape=(0, 0), dtype=float64)

In [ ]:
ones=np.ones((2,3))

In [ ]:
display(ones)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr= np.arange(5 , 10)
print(arr)

[5 6 7 8 9]


In [ ]:
arr= np.arange(5 ,)
print(arr)

[0 1 2 3 4]


In [ ]:
arr= np.arange( 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr= np.arange(0)
print(arr)

[]


In [ ]:
arr= np.arange()
print(arr)

TypeError: arange() requires stop to be specified.

In [ ]:
sequence = np.arange(0, 1, 0.2)
print("Floating-Point Sequence:", sequence)

Floating-Point Sequence: [0.  0.2 0.4 0.6 0.8]


In [ ]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
display(range_arr)

array([0, 2, 4, 6, 8])

In [ ]:
sequence = np.arange(0, 20, 3)

filtered = sequence[sequence > 10]
print("Filtered Sequence:", filtered)

Filtered Sequence: [12 15 18]


In [ ]:
# Generate 10 numbers between 0 and 1
array = np.linspace(0, 1, num=10)
print(array)



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
sequence=np.arange(0,11,5)


In [ ]:
display(sequence)

array([ 0,  5, 10])

In [ ]:
sequence=np.linspace(0,10,5)

In [ ]:
display(sequence)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
array, step = np.linspace(0, 10, num=5, retstep=True)
print( array)
print("Step Size:", step)

[ 0.   2.5  5.   7.5 10. ]
Step Size: 2.5


In [ ]:
import numpy as np

In [ ]:
# 2D Array (matrix) - farm grid
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])
print(f"\nFarm Grid:\n{farm_grid}")
print(f"Shape: {farm_grid.shape}")  # 3 rows, 3 columns


Farm Grid:
[[2500 2600 2700]
 [2800 2900 3000]
 [2400 2500 2600]]
Shape: (3, 3)


In [ ]:
import numpy as np

In [ ]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

# Access elements
print(f"First yield: {yields[0]}")
print(f"Last yield: {yields[-1]}")
print(f"First 3 yields: {yields[:3]}")

First yield: 2500
Last yield: 2700
First 3 yields: [2500 2800 3100]


In [ ]:
# 2D Array (matrix) - farm grid
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])

# 2D indexing
print(f"Center plot yield: {farm_grid[1, 1]}")
print(f"First row: {farm_grid[0]}")
print(f"Last column: {farm_grid[:, -1]}")

Center plot yield: 2900
First row: [2500 2600 2700]
Last column: [2700 3000 2600]


In [1]:
import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)

In [ ]:
import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)
mean = soil_ph.mean()
acidic_count = np.sum(soil_ph < 6.5)
highest_ph = soil_ph.max()
normalized_ph = (soil_ph - soil_ph.min()) / (soil_ph.max() - soil_ph.min())
print(mean)
print(acidic_count)
print(highest_ph)
print(normalized_ph)

6.380000000000001
5
7.3
[0.38888889 0.16666667 0.88888889 0.55555556 0.         0.72222222
 1.         0.27777778 0.22222222 0.66666667]


In [ ]:
import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)
mean = soil_ph.mean()
acidic_count = np.sum(soil_ph < 6.5)
highest_ph = soil_ph.max()
normalized_ph = (soil_ph - soil_ph.min()) / (soil_ph.max() - soil_ph.min())
print("mean value =",mean)
print("acidic_count=" , acidic_count)
print("Maximum pH =",highest_ph)
print("normalized pH=" , normalized_ph)

mean value = 6.380000000000001
acidic_count= 5
Maximum pH = 7.3
normalized pH= [0.38888889 0.16666667 0.88888889 0.55555556 0.         0.72222222
 1.         0.27777778 0.22222222 0.66666667]


In [ ]:
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
display(arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
display(arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

array([1, 2, 3])

array([[1, 2, 3],
       [4, 5, 6]])

[1 3 2]


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[2:, 1::2]
print ("first 2 rows and alternate columns(1 and 3)\n:", arr2)

# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

first 2 rows and alternate columns(1 and 3)
: [[ 0.  8.]
 [-7.  2.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
# Printing elements at
# specific Indices
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

arr4 = arr[1,3]
print("\nElements at index (1, 3) is",arr4)

arr5 = arr[1,2]
print("\nElements at index (1, 2) is",arr5)

arr6 = arr[0,1]
print("\nElements at index (0, 1) is",arr6)

arr7 = arr[3,0]
print("\nElements at index (3, 0) is",arr7)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]

Elements at index (1, 3) is 0.0

Elements at index (1, 2) is 6.0

Elements at index (0, 1) is 2.0

Elements at index (3, 0) is 3.0


In [ ]:
import numpy as np

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding 1 to every element
print ("Adding 1 to every element:\n", a + 1)

# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:\n", b - 2)

# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements:\n ", a.sum())

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element:
 [[2 3]
 [4 5]]

Subtracting 2 from each element:
 [[ 2  1]
 [ 0 -1]]

Sum of all array elements:
  10

Array sum:
 [[5 5]
 [5 5]]


In [ ]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])

# === ARRAY OPERATIONS ===
print("\n=== Array Operations ===")

# Math on entire arrays (vectorized!)
yields_tons = yields / 1000
print(f"Yields in tons: {yields_tons}")

# Bonus calculation
bonus = np.where(yields > 2800, 500, 0)
print(f"Bonus per plot: {bonus}")

# Statistics
print(f"\nTotal yield: {np.sum(yields)} kg")
print(f"Average: {np.mean(yields):.0f} kg")
print(f"Std Dev: {np.std(yields):.0f} kg")
print(f"Max: {np.max(yields)} kg, Min: {np.min(yields)} kg")

# Boolean filtering
high_yield_plots = yields[yields > 2700]
print(f"High yield plots (>2700): {high_yield_plots}")


=== Array Operations ===
Yields in tons: [2.5 2.8 3.1 2.9 2.7]
Bonus per plot: [  0   0 500 500   0]

Total yield: 14000 kg
Average: 2800 kg
Std Dev: 200 kg
Max: 3100 kg, Min: 2500 kg
High yield plots (>2700): [2800 3100 2900]


In [2]:
# Addition of Matrices
import numpy as np
Array1 = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
Array2 = np.matrix( [ [ 10, 11, 12 ],
                      [ 13, 14, 15 ],
                      [ 16, 17, 18 ] ] )
print("Output : \n",Array1+ Array2)

Output : 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [3]:
# subtraction of Matrices
import numpy as np
Array1 = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
Array2 = np.matrix( [ [ 10, 11, 12 ],
                      [ 13, 14, 15 ],
                      [ 16, 17, 18 ] ] )
print("Output : \n",Array1- Array2)

Output : 
 [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [6]:
# Multiply or divide a matrix by a scalar
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
multiplyByScalar = 5* Array
DivideByScalar = Array / 10
print("Output of product between an Array and scalar : \n", multiplyByScalar)
print("Output of division between an Array and scalar : \n", DivideByScalar)

Output of product between an Array and scalar : 
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Output of division between an Array and scalar : 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [7]:
# Finding the maximum value in the matrix
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )

print("Max value in the matrix : ", np.amax(Array))
print("Max value in the matrix along axis 0 : ", np.amax(Array, axis=0))

Max value in the matrix :  9
Max value in the matrix along axis 0 :  [[7 8 9]]


In [8]:
# Finding the minimum value in the matrix
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )

print("Min value in the matrix : ", np.amin(Array))
print("Min value in the matrix along axis 0 : ", np.amin(Array, axis=0))
print("Min value in the matrix along axis 1 : ", np.amin(Array, axis=1))

Min value in the matrix :  1
Min value in the matrix along axis 0 :  [[1 2 3]]
Min value in the matrix along axis 1 :  [[1]
 [4]
 [7]]


In [9]:
# Finding the sum of all values in the matrix
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )

print("Sum of all values in the matrix : ", np.sum(Array))

Sum of all values in the matrix :  45


In [10]:
# Dot product
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
print("Dot product : \n",np.dot(Array2 , Array1))

Dot product : 
 32


In [11]:
#cross product
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
print("cross product : \n",np.cross(Array2 , Array1))

Dot product : 
 [ 3 -6  3]


In [12]:
import numpy as np
a = [[1, 2], [2, 3]]
b = [[4, 5], [6, 7]]

print("Matrix A:")
print(a)
print("Matrix B:")
print(b)

c = np.dot(a, b)
print("Result:")
print(c)

Matrix A:
[[1, 2], [2, 3]]
Matrix B:
[[4, 5], [6, 7]]
Result:
[[16 19]
 [26 31]]


In [13]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6]]
y = [[4, 5, 1], [6, 7, 2], [7, 8, 9]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
Matrix Y:
[[4, 5, 1], [6, 7, 2], [7, 8, 9]]
Result:
[[ 37  43  32]
 [ 54  63  44]
 [ 88 103  68]]


In [14]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6], [1, 2, 3]]
y = [[4], [6], [7]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6], [1, 2, 3]]
Matrix Y:
[[4], [6], [7]]
Result:
[[37]
 [54]
 [88]
 [37]]


In [15]:
import numpy as np

# === MATRIX CREATION ===
print("=== Matrix Creation ===")

# Farm data: 3 plots, 4 factors each
# Columns: temp, rain, pH, fertilizer
farm_factors = np.array([
    [28, 150, 6.5, 50],
    [30, 120, 6.8, 45],
    [26, 180, 6.2, 60]
])
print(f"Farm Factors (3x4):\n{farm_factors}")

# Weights for yield prediction
weights = np.array([[10], [5], [100], [20]])  # 4x1
print(f"\nWeights (4x1):\n{weights.flatten()}")

# === MATRIX MULTIPLICATION ===
print("\n=== Matrix Multiplication ===")

# Predicted yields = factors @ weights + base
base_yield = 1000
predicted_yields = farm_factors @ weights + base_yield
print(f"Predicted Yields:\n{predicted_yields.flatten()}")

# === TRANSPOSE ===
print("\n=== Transpose ===")
print(f"Original shape: {farm_factors.shape}")
print(f"Transposed shape: {farm_factors.T.shape}")
print(f"Transposed:\n{farm_factors.T}")

# === ELEMENT-WISE VS MATRIX OPERATIONS ===
print("\n=== Element-wise vs Matrix ===")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A * B (element-wise):\n{A * B}")
print(f"A @ B (matrix multiply):\n{A @ B}")

# === PRACTICAL: NUTRIENT CALCULATION ===
print("\n=== Fertilizer Mix Calculation ===")
# NPK requirements per crop (kg/ha)
npk_needs = np.array([
    [120, 60, 40],   # Wheat
    [100, 50, 50],   # Rice
    [80, 40, 30]     # Millet
])

# Area of each crop (hectares)
areas = np.array([[5], [3], [2]])  # Column vector

# Total NPK needed = crops × areas
total_npk = npk_needs.T @ areas
print(f"Total N needed: {total_npk[0][0]} kg")
print(f"Total P needed: {total_npk[1][0]} kg")
print(f"Total K needed: {total_npk[2][0]} kg")

=== Matrix Creation ===
Farm Factors (3x4):
[[ 28.  150.    6.5  50. ]
 [ 30.  120.    6.8  45. ]
 [ 26.  180.    6.2  60. ]]

Weights (4x1):
[ 10   5 100  20]

=== Matrix Multiplication ===
Predicted Yields:
[3680. 3480. 3980.]

=== Transpose ===
Original shape: (3, 4)
Transposed shape: (4, 3)
Transposed:
[[ 28.   30.   26. ]
 [150.  120.  180. ]
 [  6.5   6.8   6.2]
 [ 50.   45.   60. ]]

=== Element-wise vs Matrix ===
A * B (element-wise):
[[ 5 12]
 [21 32]]
A @ B (matrix multiply):
[[19 22]
 [43 50]]

=== Fertilizer Mix Calculation ===
Total N needed: 1060 kg
Total P needed: 530 kg
Total K needed: 410 kg
